{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.consensus",
    "module": "consensus-build-configurations",
    "version": "0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "consensus-build-configurations-0.16.0.jar",
          "url": "consensus-build-configurations-0.16.0.jar",
          "size": 38410,
          "sha512": "9e9a75a9b8f06da1f622d1262e58db52dd866097ed1cd5e53276c2a5dfef2bb7f461ee7b32a06691c369d88753c7080f80aee354ac37ee8adc2d246ad14bc255",
          "sha256": "4413dbb5bf431ea4ca78234b90ff99e1dbfa287bd515efa6a8deb34b1db4eca2",
          "sha1": "305460e93e61c9bbfa61acfdcb11fedf4198ba60",
          "md5": "777442fe809249a83a1e4430a999c59d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.consensus",
          "module": "consensus-api",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "me.omico.elucidator",
          "module": "elucidator",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "consensus-build-configurations-0.16.0.jar",
          "url": "consensus-build-configurations-0.16.0.jar",
          "size": 38410,
          "sha512": "9e9a75a9b8f06da1f622d1262e58db52dd866097ed1cd5e53276c2a5dfef2bb7f461ee7b32a06691c369d88753c7080f80aee354ac37ee8adc2d246ad14bc255",
          "sha256": "4413dbb5bf431ea4ca78234b90ff99e1dbfa287bd515efa6a8deb34b1db4eca2",
          "sha1": "305460e93e61c9bbfa61acfdcb11fedf4198ba60",
          "md5": "777442fe809249a83a1e4430a999c59d"
        }
      ]
    }
  ]
}
