{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-compose/0.10.1/delusion-compose-0.10.1.module",
    "group": "me.omico.delusion",
    "module": "delusion-compose",
    "version": "0.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-compose-wasm-js-0.10.1.klib",
          "url": "delusion-compose-wasm-js-0.10.1.klib",
          "size": 17082,
          "sha512": "8f4bbc6cf6700bf18ec86149340c86e9e897ab1b6b34767d0192a7ba38620c865efbd1d5bf07327a79ccf85f0280b160e51f8d7a81c8c1ec27c52418e5cdd941",
          "sha256": "543f022afa8b67962a4e16800beea0374d690da363fc8bac6c16d1bbfa86d896",
          "sha1": "74e19e95bb34ad3c17467fb9dc0b4adac73cbb92",
          "md5": "69fff7ee0aa242e395b6d4532060b55b"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-compose-wasm-js-0.10.1.klib",
          "url": "delusion-compose-wasm-js-0.10.1.klib",
          "size": 17082,
          "sha512": "8f4bbc6cf6700bf18ec86149340c86e9e897ab1b6b34767d0192a7ba38620c865efbd1d5bf07327a79ccf85f0280b160e51f8d7a81c8c1ec27c52418e5cdd941",
          "sha256": "543f022afa8b67962a4e16800beea0374d690da363fc8bac6c16d1bbfa86d896",
          "sha1": "74e19e95bb34ad3c17467fb9dc0b4adac73cbb92",
          "md5": "69fff7ee0aa242e395b6d4532060b55b"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-compose-0.10.1.kotlin_resources.zip",
          "url": "delusion-compose-wasm-js-0.10.1-kotlin_resources.kotlin_resources.zip",
          "size": 318,
          "sha512": "e4f9de7c7bac8aa2eb977827f1bb2f4a63faa96c5433b540a706d13df4ef2f50db67922b293a0a65b0dc371b42c2195234449b18b2f4951eb0e3617c47bc8af4",
          "sha256": "43dd7a04cd4956f37be35c2ac3558102c87a23789e061c70f7538b46eb9cd01b",
          "sha1": "d1264f9b51ac9d917b77a642d8b2bf467ece3061",
          "md5": "c75b838d1a26458161890ab376a72629"
        }
      ]
    }
  ]
}
