{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-parcelize/0.11.1/delusion-parcelize-0.11.1.module",
    "group": "me.omico.delusion",
    "module": "delusion-parcelize",
    "version": "0.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-parcelize.klib",
          "url": "delusion-parcelize-macosx64-0.11.1.klib",
          "size": 11406,
          "sha512": "21fe9421695ce4f964e521a85d6ea59dd1dad34440cad88c799b5c230a3f88f522ded2b7a1638b15b20cf9d6d03c0d2d68f13c55d0412f27883ef05cdf3a1ef4",
          "sha256": "26f2da45061be0934c7391747b0a6ac761a5446a353e2453062acac142f13df5",
          "sha1": "ec75600aff6361a42db0083a7e68075ffce2dc30",
          "md5": "fbbd0d2adbce84a4597d0b2df138a90e"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-parcelize-macosx64-0.11.1-metadata.jar",
          "url": "delusion-parcelize-macosx64-0.11.1-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
