{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.gradm",
    "module": "gradm-codegen",
    "version": "4.0.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradm-codegen-4.0.0-beta02.jar",
          "url": "gradm-codegen-4.0.0-beta02.jar",
          "size": 96204,
          "sha512": "05cb44015b711d09712bccf6730361cd726636243f22bd7d01d5ba4d187d7d884574d404a419519f9a2a4bb3409ec8c701dfd7d9bb08f7f9c8afde2bc15b648a",
          "sha256": "c015dba385f041a3ef3d5abe7a8c06403f85ebaf0ef19fc3005ce8786c3aba19",
          "sha1": "64ac8b76c03bf797f1279240953813275f64274c",
          "md5": "9f6992ff3a87f3a0cb12f9aafe413d0f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.elucidator",
          "module": "elucidator",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradm-codegen-4.0.0-beta02.jar",
          "url": "gradm-codegen-4.0.0-beta02.jar",
          "size": 96204,
          "sha512": "05cb44015b711d09712bccf6730361cd726636243f22bd7d01d5ba4d187d7d884574d404a419519f9a2a4bb3409ec8c701dfd7d9bb08f7f9c8afde2bc15b648a",
          "sha256": "c015dba385f041a3ef3d5abe7a8c06403f85ebaf0ef19fc3005ce8786c3aba19",
          "sha1": "64ac8b76c03bf797f1279240953813275f64274c",
          "md5": "9f6992ff3a87f3a0cb12f9aafe413d0f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradm-codegen-4.0.0-beta02-sources.jar",
          "url": "gradm-codegen-4.0.0-beta02-sources.jar",
          "size": 9423,
          "sha512": "c00db4b449d81a9b9df13e3644e042a21dc4d5cc1c30f7365ec908bae24bee1c64ab8acfa2bd6cbbec95aeb7b27dc19962b0773d672e6ad397198b91306f6cea",
          "sha256": "a1a2f059c78a2b6e7ad58bc6d3e73234105e217557f1c4f857ef61b68f241a46",
          "sha1": "1413715a1030ff1bcc9bad5c7b6859fbe5443865",
          "md5": "ab754995b303e10ee9df31c143f0383d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradm-codegen-4.0.0-beta02-javadoc.jar",
          "url": "gradm-codegen-4.0.0-beta02-javadoc.jar",
          "size": 261,
          "sha512": "720f50fadc89825c4af0bb32bf25fbee11d6be0822edf52d119bb562353a6e1bf5e6c2adaae878132de14881c7ad0cf61afbfc611d656e9d193cc2d34cb49c59",
          "sha256": "ca0a933dde98b84f22a0ca84a31d215f0e5d3a93218fdc2f3e6bbdad9d7d598e",
          "sha1": "b06eb974fa5dbd6d0447d4d33b727e1648d4b7c6",
          "md5": "67e034004aab96e792506c53ffc2729c"
        }
      ]
    }
  ]
}
