{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-logger/0.3.0/delusion-logger-0.3.0.module",
    "group": "me.omico.delusion",
    "module": "delusion-logger",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm",
        "project.target.platform.type": "android"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-logger-release.aar",
          "url": "delusion-logger-android-0.3.0.aar",
          "size": 12977,
          "sha512": "e7ea09d6e8c22c1d673ddd9b9e86292cd5a2cb57f7ba34f1a69cc8183cd36b04632126e8c276d09f0f788d1628a5d2075f573611751b96ed4f0b032cb09de044",
          "sha256": "a7c9c1776a91b88036e66317563d9aa1b7466dda3aaaa40bc3456221eb9c54b3",
          "sha1": "133082e023674c7ac5cd90752be7daffafea22b2",
          "md5": "aab1cab79ece645a92aef6a26c7c91da"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm",
        "project.target.platform.type": "android"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "delusion-logger-release.aar",
          "url": "delusion-logger-android-0.3.0.aar",
          "size": 12977,
          "sha512": "e7ea09d6e8c22c1d673ddd9b9e86292cd5a2cb57f7ba34f1a69cc8183cd36b04632126e8c276d09f0f788d1628a5d2075f573611751b96ed4f0b032cb09de044",
          "sha256": "a7c9c1776a91b88036e66317563d9aa1b7466dda3aaaa40bc3456221eb9c54b3",
          "sha1": "133082e023674c7ac5cd90752be7daffafea22b2",
          "md5": "aab1cab79ece645a92aef6a26c7c91da"
        }
      ]
    }
  ]
}
