{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-parcelize/0.11.2/delusion-parcelize-0.11.2.module",
    "group": "me.omico.delusion",
    "module": "delusion-parcelize",
    "version": "0.11.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-parcelize.klib",
          "url": "delusion-parcelize-macosarm64-0.11.2.klib",
          "size": 11427,
          "sha512": "63a51bee6e7e3ffe74eca489cb9170a3d544bb441d44ce749ff5d841b727f67677833ad4d6805329582dc3c71da5723d09dac33b2ad55e3f8039483fe69790b4",
          "sha256": "cf400114393e38c50af8f859b7909b8c2d64fec12610faf3ed6017f5c8a4d0b1",
          "sha1": "3c79132fc8697308419e06fbedc7bad1e987fe8d",
          "md5": "cc34ff9564a1bcad9040514525c29ea0"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-parcelize-macosarm64-0.11.2-metadata.jar",
          "url": "delusion-parcelize-macosarm64-0.11.2-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
