{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-compose/0.3.0/delusion-compose-0.3.0.module",
    "group": "me.omico.delusion",
    "module": "delusion-compose",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "project.target.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-compose-jvm-0.3.0.jar",
          "url": "delusion-compose-jvm-0.3.0.jar",
          "size": 11973,
          "sha512": "5a94292ebf77da5654c7382dd52a8aeab46cc28267c4708b82aa8289b25f53b18f063ab74230fe7f7ad4c4c013ac6259bcd703c9e29b86c93ceb0fa6febf8212",
          "sha256": "9b787297084a9cc4a795eed57772132d0b7394eb7dc9d4f4e0c743f17f3538a1",
          "sha1": "9bfd2d8a7cceea6ef9825ef07f483c52110c1726",
          "md5": "ad7d9075d8ddaa09eae6f502549842e3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "project.target.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-compose-jvm-0.3.0.jar",
          "url": "delusion-compose-jvm-0.3.0.jar",
          "size": 11973,
          "sha512": "5a94292ebf77da5654c7382dd52a8aeab46cc28267c4708b82aa8289b25f53b18f063ab74230fe7f7ad4c4c013ac6259bcd703c9e29b86c93ceb0fa6febf8212",
          "sha256": "9b787297084a9cc4a795eed57772132d0b7394eb7dc9d4f4e0c743f17f3538a1",
          "sha1": "9bfd2d8a7cceea6ef9825ef07f483c52110c1726",
          "md5": "ad7d9075d8ddaa09eae6f502549842e3"
        }
      ]
    }
  ]
}
