{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.kami",
    "module": "kami-kotlin-embedded",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.kami",
          "module": "kami-core",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.21-1.0.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.compose",
          "module": "org.jetbrains.kotlin.plugin.compose.gradle.plugin",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.parcelize",
          "module": "org.jetbrains.kotlin.plugin.parcelize.gradle.plugin",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kami-kotlin-embedded-0.2.0.jar",
          "url": "kami-kotlin-embedded-0.2.0.jar",
          "size": 81364,
          "sha512": "f4d77d319d176980a46f4270530eff35c84d1c5c9c22bac4e086df7299c6c187a8766d10254fcf102e20da3c20e62f0d91ca56abef356105a0df6579f9013158",
          "sha256": "3a95eeb9eb5daa07442fee0ec0737bebd625acc65c7d65ac3171b142f44970d0",
          "sha1": "7f23ac19a181168ecdfb3759f4867a9f166563c0",
          "md5": "b81db9a67b3688225047de533e3f5304"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.kami",
          "module": "kami-core",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.21-1.0.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.compose",
          "module": "org.jetbrains.kotlin.plugin.compose.gradle.plugin",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.parcelize",
          "module": "org.jetbrains.kotlin.plugin.parcelize.gradle.plugin",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kami-kotlin-embedded-0.2.0.jar",
          "url": "kami-kotlin-embedded-0.2.0.jar",
          "size": 81364,
          "sha512": "f4d77d319d176980a46f4270530eff35c84d1c5c9c22bac4e086df7299c6c187a8766d10254fcf102e20da3c20e62f0d91ca56abef356105a0df6579f9013158",
          "sha256": "3a95eeb9eb5daa07442fee0ec0737bebd625acc65c7d65ac3171b142f44970d0",
          "sha1": "7f23ac19a181168ecdfb3759f4867a9f166563c0",
          "md5": "b81db9a67b3688225047de533e3f5304"
        }
      ]
    }
  ]
}
