{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-compose/0.11.2/delusion-compose-0.11.2.module",
    "group": "me.omico.delusion",
    "module": "delusion-compose",
    "version": "0.11.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-compose-desktop-0.11.2.jar",
          "url": "delusion-compose-desktop-0.11.2.jar",
          "size": 62227,
          "sha512": "6e4930856bae0a5b64a5f7261acd1f920c71ca83809d191b36c10accd0a1cafbef1faedae7e918e90e44d102a89f44168c7ff0722b49bd4a7c023528625c8fa4",
          "sha256": "9c9659f59b136ce0e7215c7845f05d45b51c71e9b7ec8959639fe52e90956b12",
          "sha1": "f96e8e13b84d9e648477a423bb560ace01d41bf4",
          "md5": "c882832507b4fe21b1d7c0aae264f513"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "me.omico.delusion",
          "module": "delusion-core",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "me.omico.delusion",
          "module": "delusion-jna",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "com.github.hypfvieh",
          "module": "dbus-java-core",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.github.hypfvieh",
          "module": "dbus-java-transport-junixsocket",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-compose-desktop-0.11.2.jar",
          "url": "delusion-compose-desktop-0.11.2.jar",
          "size": 62227,
          "sha512": "6e4930856bae0a5b64a5f7261acd1f920c71ca83809d191b36c10accd0a1cafbef1faedae7e918e90e44d102a89f44168c7ff0722b49bd4a7c023528625c8fa4",
          "sha256": "9c9659f59b136ce0e7215c7845f05d45b51c71e9b7ec8959639fe52e90956b12",
          "sha1": "f96e8e13b84d9e648477a423bb560ace01d41bf4",
          "md5": "c882832507b4fe21b1d7c0aae264f513"
        }
      ]
    }
  ]
}
