{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.consensus",
    "module": "consensus-build-configurations",
    "version": "0.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "consensus-build-configurations-0.17.1.jar",
          "url": "consensus-build-configurations-0.17.1.jar",
          "size": 39493,
          "sha512": "5d90df6301d352c8a59bef07cf90edf1f918ee0c40ac9fd7f2037a1666d7d3de9f5fe76a7825ec9004a7223ac08db069952a76f2f15ef37eea6f4c68631d27ef",
          "sha256": "050665a5d319100da640d372fe4ec6c0b124d4798a36663e5a57e66b6116041a",
          "sha1": "046d9707438b664995107eb583dc070532dd8724",
          "md5": "69f37cf8729bbcdfc601ea45b55b884b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.consensus",
          "module": "consensus-api",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "me.omico.elucidator",
          "module": "elucidator",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "consensus-build-configurations-0.17.1.jar",
          "url": "consensus-build-configurations-0.17.1.jar",
          "size": 39493,
          "sha512": "5d90df6301d352c8a59bef07cf90edf1f918ee0c40ac9fd7f2037a1666d7d3de9f5fe76a7825ec9004a7223ac08db069952a76f2f15ef37eea6f4c68631d27ef",
          "sha256": "050665a5d319100da640d372fe4ec6c0b124d4798a36663e5a57e66b6116041a",
          "sha1": "046d9707438b664995107eb583dc070532dd8724",
          "md5": "69f37cf8729bbcdfc601ea45b55b884b"
        }
      ]
    }
  ]
}
