{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-jna/0.6.0/delusion-jna-0.6.0.module",
    "group": "me.omico.delusion",
    "module": "delusion-jna",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-jna-jvm-0.6.0.jar",
          "url": "delusion-jna-jvm-0.6.0.jar",
          "size": 11867,
          "sha512": "552dd99f749c59ed52d5c315e5cf645577721dd334fc02188f7ec638656301700dfb4c59dd35ab90977f3059c13578b4e0a6bd01c67bbeb26f01b161698fdc8f",
          "sha256": "e36a599046c58a80a417e8d7fa41b582e2cd6c343c90d6aacf42ac0c3a234e61",
          "sha1": "efb189f1fdd3d154579e39d0260e60ef3cda0397",
          "md5": "ec916a4244ef71d07aa787900e7919b3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "me.omico.delusion",
          "module": "delusion-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-jna-jvm-0.6.0.jar",
          "url": "delusion-jna-jvm-0.6.0.jar",
          "size": 11867,
          "sha512": "552dd99f749c59ed52d5c315e5cf645577721dd334fc02188f7ec638656301700dfb4c59dd35ab90977f3059c13578b4e0a6bd01c67bbeb26f01b161698fdc8f",
          "sha256": "e36a599046c58a80a417e8d7fa41b582e2cd6c343c90d6aacf42ac0c3a234e61",
          "sha1": "efb189f1fdd3d154579e39d0260e60ef3cda0397",
          "md5": "ec916a4244ef71d07aa787900e7919b3"
        }
      ]
    }
  ]
}
