{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.consensus",
    "module": "consensus-spotless",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "consensus-spotless-0.6.0.jar",
          "url": "consensus-spotless-0.6.0.jar",
          "size": 31674,
          "sha512": "33029c2857d7b114f21906ecd847e7b9ccdae5f9ee78a7440629827e27a5463670c617365c25cfcb093e2d8539430b4eab2025fe4411145b8d3d11f3d4bcb43f",
          "sha256": "81d17a9865302439a2649498ff7ec8c1bf9933231f88592f8264ffb1f2255d3d",
          "sha1": "0569a0ca38f7820b724709a29385f2fc49e7988c",
          "md5": "67c0a3504832cffb9136d20eadda5c1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.consensus",
          "module": "consensus-api",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-dsl",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "consensus-spotless-0.6.0.jar",
          "url": "consensus-spotless-0.6.0.jar",
          "size": 31674,
          "sha512": "33029c2857d7b114f21906ecd847e7b9ccdae5f9ee78a7440629827e27a5463670c617365c25cfcb093e2d8539430b4eab2025fe4411145b8d3d11f3d4bcb43f",
          "sha256": "81d17a9865302439a2649498ff7ec8c1bf9933231f88592f8264ffb1f2255d3d",
          "sha1": "0569a0ca38f7820b724709a29385f2fc49e7988c",
          "md5": "67c0a3504832cffb9136d20eadda5c1f"
        }
      ]
    }
  ]
}
