{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-kotlinx-io/0.11.1/delusion-kotlinx-io-0.11.1.module",
    "group": "me.omico.delusion",
    "module": "delusion-kotlinx-io",
    "version": "0.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "webApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-kotlinx-io-web-0.11.1.klib",
          "url": "delusion-kotlinx-io-web-0.11.1.klib",
          "size": 5337,
          "sha512": "e82216beb2aaa3fb6ae29b30ce38d6c09b995590a84f99efedd56495d70d72182f7590423c01d065aa054150460ff6c663bfd98b717bf47e49b125341ee1b58d",
          "sha256": "7b9f08d8af308d12a448d010b31df2a55c73d18720215b06c107ce5e4bc91379",
          "sha1": "5cae70db2ca7352d06ce7a192e110111abdc1b29",
          "md5": "c97194b0c0f6d83816ab25e67a6d3810"
        }
      ]
    },
    {
      "name": "webRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-kotlinx-io-web-0.11.1.klib",
          "url": "delusion-kotlinx-io-web-0.11.1.klib",
          "size": 5337,
          "sha512": "e82216beb2aaa3fb6ae29b30ce38d6c09b995590a84f99efedd56495d70d72182f7590423c01d065aa054150460ff6c663bfd98b717bf47e49b125341ee1b58d",
          "sha256": "7b9f08d8af308d12a448d010b31df2a55c73d18720215b06c107ce5e4bc91379",
          "sha1": "5cae70db2ca7352d06ce7a192e110111abdc1b29",
          "md5": "c97194b0c0f6d83816ab25e67a6d3810"
        }
      ]
    }
  ]
}
