{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.consensus",
    "module": "consensus-publishing",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "consensus-publishing-0.9.0.jar",
          "url": "consensus-publishing-0.9.0.jar",
          "size": 36646,
          "sha512": "4a371710edf34f1b4c7747858793856edc9e5764b79985ddced0edae21cad7597fcf0e040fefce2927b18467b38f11ea8abc85a3319e4d14954d8e337fb346b4",
          "sha256": "f674f752ef9aecce873e255d61b3690398239005d4d5a7ad5d07420435b810b6",
          "sha1": "0d38f11098869563087f4c807da5d9a950dfe01d",
          "md5": "f31dd0ff113e64a185c8be81067e15a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.consensus",
          "module": "consensus-api",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-dsl",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "consensus-publishing-0.9.0.jar",
          "url": "consensus-publishing-0.9.0.jar",
          "size": 36646,
          "sha512": "4a371710edf34f1b4c7747858793856edc9e5764b79985ddced0edae21cad7597fcf0e040fefce2927b18467b38f11ea8abc85a3319e4d14954d8e337fb346b4",
          "sha256": "f674f752ef9aecce873e255d61b3690398239005d4d5a7ad5d07420435b810b6",
          "sha1": "0d38f11098869563087f4c807da5d9a950dfe01d",
          "md5": "f31dd0ff113e64a185c8be81067e15a4"
        }
      ]
    }
  ]
}
