{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.consensus",
    "module": "consensus-r8",
    "version": "0.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "consensus-r8-0.19.0.jar",
          "url": "consensus-r8-0.19.0.jar",
          "size": 21327,
          "sha512": "f9521de812cdb24aa61b35e777dc4bac7cfead550706ed8b3b2cb724bed0584012346ccf8bfdfe8fda82a33a69490bc7d575ab2e0c5d33415af139e8dea7a674",
          "sha256": "fdd60912f5c88f56d05f0d41771502eafacdf0e712d20b382e0be37bf3a62369",
          "sha1": "0a143c45cc1105d6366a650f1d4634e630e02f5a",
          "md5": "e68e443e6d6cd8bf6b70aa1198019d76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.consensus",
          "module": "consensus-api",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "r8",
          "version": {
            "requires": "8.5.35"
          }
        }
      ],
      "files": [
        {
          "name": "consensus-r8-0.19.0.jar",
          "url": "consensus-r8-0.19.0.jar",
          "size": 21327,
          "sha512": "f9521de812cdb24aa61b35e777dc4bac7cfead550706ed8b3b2cb724bed0584012346ccf8bfdfe8fda82a33a69490bc7d575ab2e0c5d33415af139e8dea7a674",
          "sha256": "fdd60912f5c88f56d05f0d41771502eafacdf0e712d20b382e0be37bf3a62369",
          "sha1": "0a143c45cc1105d6366a650f1d4634e630e02f5a",
          "md5": "e68e443e6d6cd8bf6b70aa1198019d76"
        }
      ]
    }
  ]
}
