{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.kami",
    "module": "kami-compose",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.kami",
          "module": "kami-core",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose",
          "module": "org.jetbrains.compose.gradle.plugin",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "kami-compose-0.4.0.jar",
          "url": "kami-compose-0.4.0.jar",
          "size": 9978,
          "sha512": "8661856ebe8826a89d244eb4cc2d33cd75ff41bee05f9186a84014bf35c4487426fed4a992ed4f752dbefeb1ca7df25ed8b4289a24c5d723ef99a26501f7206e",
          "sha256": "e369fe9e167763e196864e6842dd83daf1356600637673af6167f6ed75488512",
          "sha1": "382534956567210c4d5937ce7b0ba078b0a98f7c",
          "md5": "a7589dc5563843d69f178228cfc935d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.kami",
          "module": "kami-core",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose",
          "module": "org.jetbrains.compose.gradle.plugin",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "kami-compose-0.4.0.jar",
          "url": "kami-compose-0.4.0.jar",
          "size": 9978,
          "sha512": "8661856ebe8826a89d244eb4cc2d33cd75ff41bee05f9186a84014bf35c4487426fed4a992ed4f752dbefeb1ca7df25ed8b4289a24c5d723ef99a26501f7206e",
          "sha256": "e369fe9e167763e196864e6842dd83daf1356600637673af6167f6ed75488512",
          "sha1": "382534956567210c4d5937ce7b0ba078b0a98f7c",
          "md5": "a7589dc5563843d69f178228cfc935d6"
        }
      ]
    }
  ]
}
