{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-kotlinx-datetime/0.4.0/delusion-kotlinx-datetime-0.4.0.module",
    "group": "me.omico.delusion",
    "module": "delusion-kotlinx-datetime",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "project.target.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-kotlinx-datetime-jvm-0.4.0.jar",
          "url": "delusion-kotlinx-datetime-jvm-0.4.0.jar",
          "size": 2993,
          "sha512": "d9f3e28b1cd8f88a1d14b6fca29862619501059507afc04df55a1e471a858444c92482d972d9dafa7fe37ff669f7f5135a532bf444401933dd97b3e0cedbf204",
          "sha256": "425d9d8ca6ff9cb21366a9a3459130deb8e76484c11d7e54cc30fd5327a8a7a6",
          "sha1": "81214ccb93ce051fa53aa9aee6edc5966d939bbe",
          "md5": "96ab89e873c4122ece069ddfa417b849"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "project.target.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-kotlinx-datetime-jvm-0.4.0.jar",
          "url": "delusion-kotlinx-datetime-jvm-0.4.0.jar",
          "size": 2993,
          "sha512": "d9f3e28b1cd8f88a1d14b6fca29862619501059507afc04df55a1e471a858444c92482d972d9dafa7fe37ff669f7f5135a532bf444401933dd97b3e0cedbf204",
          "sha256": "425d9d8ca6ff9cb21366a9a3459130deb8e76484c11d7e54cc30fd5327a8a7a6",
          "sha1": "81214ccb93ce051fa53aa9aee6edc5966d939bbe",
          "md5": "96ab89e873c4122ece069ddfa417b849"
        }
      ]
    }
  ]
}
