{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.consensus",
    "module": "consensus-initialization",
    "version": "0.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "consensus-initialization-0.17.1.jar",
          "url": "consensus-initialization-0.17.1.jar",
          "size": 33826,
          "sha512": "cc3f17a83635cef4ce6d035355a15454ce8bb97b5dfa64e23595a2765456dcc2462720e9ddef8d5f16cc568d521c8aae3cd3679418f84ac62fdbc1e3a7a218ce",
          "sha256": "f9788ebba2eb37724404824be7a091a63e4fef2e0ce2352b53f2dec54a1971f1",
          "sha1": "dbf7eec33c4fa30f62608351e2b2ffa19ebf68ce",
          "md5": "0543c59cafd9b100c33aeb0275c888cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.consensus",
          "module": "consensus-api",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "3.19"
          }
        }
      ],
      "files": [
        {
          "name": "consensus-initialization-0.17.1.jar",
          "url": "consensus-initialization-0.17.1.jar",
          "size": 33826,
          "sha512": "cc3f17a83635cef4ce6d035355a15454ce8bb97b5dfa64e23595a2765456dcc2462720e9ddef8d5f16cc568d521c8aae3cd3679418f84ac62fdbc1e3a7a218ce",
          "sha256": "f9788ebba2eb37724404824be7a091a63e4fef2e0ce2352b53f2dec54a1971f1",
          "sha1": "dbf7eec33c4fa30f62608351e2b2ffa19ebf68ce",
          "md5": "0543c59cafd9b100c33aeb0275c888cf"
        }
      ]
    }
  ]
}
