{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-compose/0.8.0/delusion-compose-0.8.0.module",
    "group": "me.omico.delusion",
    "module": "delusion-compose",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-compose-desktop-0.8.0.jar",
          "url": "delusion-compose-desktop-0.8.0.jar",
          "size": 44937,
          "sha512": "a459122c29d55c23dd7fc368f1628730155d6f24ba023d4dcfc645c43142b9a28bddb83c5289c0b36d604021659991a6782c2e8a00410e95082d36533c455901",
          "sha256": "b9736238cb27832f7d75ec8693fb3d080a87db54fe9a5f420f899b9270d0ad21",
          "sha1": "0c29429a4627d2e41311135a73d7cf741e128272",
          "md5": "64c0ce09879be08e6579a26e38f0d6ff"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "me.omico.delusion",
          "module": "delusion-core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "me.omico.delusion",
          "module": "delusion-jna",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.github.hypfvieh",
          "module": "dbus-java-core",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "com.github.hypfvieh",
          "module": "dbus-java-transport-junixsocket",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-compose-desktop-0.8.0.jar",
          "url": "delusion-compose-desktop-0.8.0.jar",
          "size": 44937,
          "sha512": "a459122c29d55c23dd7fc368f1628730155d6f24ba023d4dcfc645c43142b9a28bddb83c5289c0b36d604021659991a6782c2e8a00410e95082d36533c455901",
          "sha256": "b9736238cb27832f7d75ec8693fb3d080a87db54fe9a5f420f899b9270d0ad21",
          "sha1": "0c29429a4627d2e41311135a73d7cf741e128272",
          "md5": "64c0ce09879be08e6579a26e38f0d6ff"
        }
      ]
    }
  ]
}
