{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.kami",
    "module": "kami-kotlin",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.kami",
          "module": "kami-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.2.0-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.compose",
          "module": "org.jetbrains.kotlin.plugin.compose.gradle.plugin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.parcelize",
          "module": "org.jetbrains.kotlin.plugin.parcelize.gradle.plugin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx.atomicfu",
          "module": "org.jetbrains.kotlinx.atomicfu.gradle.plugin",
          "version": {
            "requires": "0.29.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kami-kotlin-0.6.0.jar",
          "url": "kami-kotlin-0.6.0.jar",
          "size": 88423,
          "sha512": "2ae80f7654d672efdf60182d7e6732fdd945b30b5d777073e49862148d7e001319085dad64a76c1f6d2eba3b5046dfefa573a52887cfb2a2005790586f67ad65",
          "sha256": "a25e9d5af790a574b47b208a5a163a8ff55de2d73ef6a7487ae54833c767a480",
          "sha1": "7eb81910becfc4523e23d3fa02a45262d991adc7",
          "md5": "3414b4681d5f025b377cd248b3327bb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.kami",
          "module": "kami-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.2.0-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.compose",
          "module": "org.jetbrains.kotlin.plugin.compose.gradle.plugin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.parcelize",
          "module": "org.jetbrains.kotlin.plugin.parcelize.gradle.plugin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx.atomicfu",
          "module": "org.jetbrains.kotlinx.atomicfu.gradle.plugin",
          "version": {
            "requires": "0.29.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kami-kotlin-0.6.0.jar",
          "url": "kami-kotlin-0.6.0.jar",
          "size": 88423,
          "sha512": "2ae80f7654d672efdf60182d7e6732fdd945b30b5d777073e49862148d7e001319085dad64a76c1f6d2eba3b5046dfefa573a52887cfb2a2005790586f67ad65",
          "sha256": "a25e9d5af790a574b47b208a5a163a8ff55de2d73ef6a7487ae54833c767a480",
          "sha1": "7eb81910becfc4523e23d3fa02a45262d991adc7",
          "md5": "3414b4681d5f025b377cd248b3327bb7"
        }
      ]
    }
  ]
}
