{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.elucidator",
    "module": "elucidator",
    "version": "0.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "elucidator-0.15.0.jar",
          "url": "elucidator-0.15.0.jar",
          "size": 79454,
          "sha512": "6ec74d5aa1487c858bde3132d7b4e93f58e9c8c0a42d2c0d059823aba2c23ec390272e5f2e91f5b2244b490cb2d3e8218449443d933aeeb66aa8cba0b7d49bf0",
          "sha256": "2e280e4950c583282b759a06634c5e917580b41b182bf2f68ec12b01eaada706",
          "sha1": "1dfb638db57db813fbc7ac8691d39d8dc851be34",
          "md5": "d7df8479eb227ec2a8c45c6ec19c13da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "elucidator-0.15.0.jar",
          "url": "elucidator-0.15.0.jar",
          "size": 79454,
          "sha512": "6ec74d5aa1487c858bde3132d7b4e93f58e9c8c0a42d2c0d059823aba2c23ec390272e5f2e91f5b2244b490cb2d3e8218449443d933aeeb66aa8cba0b7d49bf0",
          "sha256": "2e280e4950c583282b759a06634c5e917580b41b182bf2f68ec12b01eaada706",
          "sha1": "1dfb638db57db813fbc7ac8691d39d8dc851be34",
          "md5": "d7df8479eb227ec2a8c45c6ec19c13da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "elucidator-0.15.0-sources.jar",
          "url": "elucidator-0.15.0-sources.jar",
          "size": 19131,
          "sha512": "c3456eff4f6762876e4bca2ddb531a21c156dee070c2d26314c44357765a71338d07bff6db68eb4ba4b9b616e2176e3f1b3db95ec35871fafc9b7e9536779bbc",
          "sha256": "ec58f7d143d246e09b6babe307dc9bffc9434452b25baa03764f535564cf889a",
          "sha1": "289acb855fe76172c4ac626589728016f7bba585",
          "md5": "7de547df5b20f37edd4cc6099e1f606f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "elucidator-0.15.0-javadoc.jar",
          "url": "elucidator-0.15.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
