{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-compose/0.9.0/delusion-compose-0.9.0.module",
    "group": "me.omico.delusion",
    "module": "delusion-compose",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-compose-desktop-0.9.0.jar",
          "url": "delusion-compose-desktop-0.9.0.jar",
          "size": 39261,
          "sha512": "aba4476433302574c680adbd907b08249bbd63352128a439f6fa52f0c7d728074838b069869f3f8e54e8c86c21a6ed8acf0200909d4ec2fa6d57a9e37e3c6132",
          "sha256": "1902dc669e7abbbe292e9bfc69ecf8317d6ec0ceaccd5a8e9f7703e141ded560",
          "sha1": "4a1d0f6ae734c8841c385b4ede6c1d80eb4debcb",
          "md5": "1c07ca5cb665873665575347e1c3df56"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "me.omico.delusion",
          "module": "delusion-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "me.omico.delusion",
          "module": "delusion-jna",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.github.hypfvieh",
          "module": "dbus-java-core",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "com.github.hypfvieh",
          "module": "dbus-java-transport-junixsocket",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-compose-desktop-0.9.0.jar",
          "url": "delusion-compose-desktop-0.9.0.jar",
          "size": 39261,
          "sha512": "aba4476433302574c680adbd907b08249bbd63352128a439f6fa52f0c7d728074838b069869f3f8e54e8c86c21a6ed8acf0200909d4ec2fa6d57a9e37e3c6132",
          "sha256": "1902dc669e7abbbe292e9bfc69ecf8317d6ec0ceaccd5a8e9f7703e141ded560",
          "sha1": "4a1d0f6ae734c8841c385b4ede6c1d80eb4debcb",
          "md5": "1c07ca5cb665873665575347e1c3df56"
        }
      ]
    }
  ]
}
