{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.consensus",
    "module": "consensus-gradle-plugins",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.consensus",
          "module": "consensus-api",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-git",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-publishing",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-root",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-spotless",
          "version": {
            "requires": "0.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "consensus-gradle-plugins-0.12.0.jar",
          "url": "consensus-gradle-plugins-0.12.0.jar",
          "size": 261,
          "sha512": "cb454ef086b16d577ad7fd07754ffc003ab72f2f521b6b29c0c570db5c3d851524e72b6cd9273b81259611c3c7cb4acc82d5760b67dfaeb55eb657acbf54d12d",
          "sha256": "58159f77384d9617b68f3bf7ca4f921a798812400787f65387c14972e7b25db5",
          "sha1": "03e381a8aea74187ec4f6ec3d0b01b0bb1bce5ab",
          "md5": "715aad82cc77bffc979943f14baa61d6"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.consensus",
          "module": "consensus-api",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-git",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-publishing",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-root",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-spotless",
          "version": {
            "requires": "0.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "consensus-gradle-plugins-0.12.0.jar",
          "url": "consensus-gradle-plugins-0.12.0.jar",
          "size": 261,
          "sha512": "cb454ef086b16d577ad7fd07754ffc003ab72f2f521b6b29c0c570db5c3d851524e72b6cd9273b81259611c3c7cb4acc82d5760b67dfaeb55eb657acbf54d12d",
          "sha256": "58159f77384d9617b68f3bf7ca4f921a798812400787f65387c14972e7b25db5",
          "sha1": "03e381a8aea74187ec4f6ec3d0b01b0bb1bce5ab",
          "md5": "715aad82cc77bffc979943f14baa61d6"
        }
      ]
    }
  ]
}
