{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-okio/0.9.0/delusion-okio-0.9.0.module",
    "group": "me.omico.delusion",
    "module": "delusion-okio",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-okio.klib",
          "url": "delusion-okio-mingwx64-0.9.0.klib",
          "size": 10446,
          "sha512": "4c6c60ba95f12a9e2a1a4f85754d5a9e5f6695af8553bebc04421924b3a4d1c074cacb90227dd924d094eb6ba8d235f720b05eb0165293d64a99ec647142ff7e",
          "sha256": "4458851287d69c2dd8e6fb14209d4a57bfd142a51e21ea9f8ac24c9a2abadb46",
          "sha1": "7e9090c539b6f2a9da7e2af52fec5f4a38320e83",
          "md5": "af8ae1ecb1c622a7dc200639e30aa6ef"
        }
      ]
    }
  ]
}
