{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-compose/0.8.1/delusion-compose-0.8.1.module",
    "group": "me.omico.delusion",
    "module": "delusion-compose",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-compose-release.aar",
          "url": "delusion-compose-android-0.8.1.aar",
          "size": 14545,
          "sha512": "bcc2fdaae2211c93f24f2b2cd9c7e542897fa00f61ccc97955cddcc18c617f306ca835548795e001310710190fb282b9606e7fa9b305ac21ea08456ca5e84858",
          "sha256": "3f5ec6ffb9ee8ad41470efe6479059f1910bdaad1a9815c88af43d21e48c9f4d",
          "sha1": "b81b1d82ee6928ebf6d3cdc8d99f57fb6bf5bd3b",
          "md5": "6fa282609f80686b43547b9a68819d42"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "delusion-compose-release.aar",
          "url": "delusion-compose-android-0.8.1.aar",
          "size": 14545,
          "sha512": "bcc2fdaae2211c93f24f2b2cd9c7e542897fa00f61ccc97955cddcc18c617f306ca835548795e001310710190fb282b9606e7fa9b305ac21ea08456ca5e84858",
          "sha256": "3f5ec6ffb9ee8ad41470efe6479059f1910bdaad1a9815c88af43d21e48c9f4d",
          "sha1": "b81b1d82ee6928ebf6d3cdc8d99f57fb6bf5bd3b",
          "md5": "6fa282609f80686b43547b9a68819d42"
        }
      ]
    }
  ]
}
