{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.kami",
    "module": "kami-kotlin-embedded",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.kami",
          "module": "kami-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.2.20-2.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.compose",
          "module": "org.jetbrains.kotlin.plugin.compose.gradle.plugin",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.parcelize",
          "module": "org.jetbrains.kotlin.plugin.parcelize.gradle.plugin",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx.atomicfu",
          "module": "org.jetbrains.kotlinx.atomicfu.gradle.plugin",
          "version": {
            "requires": "0.29.0"
          }
        }
      ],
      "files": [
        {
          "name": "kami-kotlin-embedded-0.7.0.jar",
          "url": "kami-kotlin-embedded-0.7.0.jar",
          "size": 101841,
          "sha512": "75a98d867fe2715e5ed16262e2200163828a37474f2def1422540724baa34a38616f1652dbe2a14b687aabb1fad614cf26251c134df1b5853ab3fb516bf2e507",
          "sha256": "a5d1d224235db268043d74d43b7b7310969fc5cf52de5feeaa73cb9097c44486",
          "sha1": "b84a0ba568376e617b0b6a225a7f20ba0853f788",
          "md5": "5d54b04b34db7cd3f41ef24be581ddcf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.kami",
          "module": "kami-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.2.20-2.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.compose",
          "module": "org.jetbrains.kotlin.plugin.compose.gradle.plugin",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.parcelize",
          "module": "org.jetbrains.kotlin.plugin.parcelize.gradle.plugin",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx.atomicfu",
          "module": "org.jetbrains.kotlinx.atomicfu.gradle.plugin",
          "version": {
            "requires": "0.29.0"
          }
        }
      ],
      "files": [
        {
          "name": "kami-kotlin-embedded-0.7.0.jar",
          "url": "kami-kotlin-embedded-0.7.0.jar",
          "size": 101841,
          "sha512": "75a98d867fe2715e5ed16262e2200163828a37474f2def1422540724baa34a38616f1652dbe2a14b687aabb1fad614cf26251c134df1b5853ab3fb516bf2e507",
          "sha256": "a5d1d224235db268043d74d43b7b7310969fc5cf52de5feeaa73cb9097c44486",
          "sha1": "b84a0ba568376e617b0b6a225a7f20ba0853f788",
          "md5": "5d54b04b34db7cd3f41ef24be581ddcf"
        }
      ]
    }
  ]
}
