{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-jna/0.6.1/delusion-jna-0.6.1.module",
    "group": "me.omico.delusion",
    "module": "delusion-jna",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-jna-jvm-0.6.1.jar",
          "url": "delusion-jna-jvm-0.6.1.jar",
          "size": 11866,
          "sha512": "47cb89558698f75949867d93f37608ed5ffe9436d6e09c5b9beb0145a7be0dd7711bf29b8cc7e16319ce3625bdb398c314e4b0c477bf9fe43c64f94247118b2c",
          "sha256": "f94ab7b7dec484ea8b6e0c360db3f300ddc4af4d566e4e2b39b52e13fc11c5fd",
          "sha1": "b57c51da7a2eb3aa2873cd2d46ee12d32ae34dd2",
          "md5": "3ba060c7f11f023fc617df23ba2c5606"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "me.omico.delusion",
          "module": "delusion-core",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-jna-jvm-0.6.1.jar",
          "url": "delusion-jna-jvm-0.6.1.jar",
          "size": 11866,
          "sha512": "47cb89558698f75949867d93f37608ed5ffe9436d6e09c5b9beb0145a7be0dd7711bf29b8cc7e16319ce3625bdb398c314e4b0c477bf9fe43c64f94247118b2c",
          "sha256": "f94ab7b7dec484ea8b6e0c360db3f300ddc4af4d566e4e2b39b52e13fc11c5fd",
          "sha1": "b57c51da7a2eb3aa2873cd2d46ee12d32ae34dd2",
          "md5": "3ba060c7f11f023fc617df23ba2c5606"
        }
      ]
    }
  ]
}
