{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.gradm",
    "module": "gradm-integration-api",
    "version": "4.0.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.gradm",
          "module": "gradm-runtime",
          "version": {
            "requires": "4.0.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradm-integration-api-4.0.0-beta03.jar",
          "url": "gradm-integration-api-4.0.0-beta03.jar",
          "size": 27446,
          "sha512": "b0a1f25b99c0009d25250057fd3a54a6d3750773df3abf4e03bbee1f5d3e60c42c43bbee71ae95623d7c68df85771d39c18a324c5958dab3d4355aab7730ccd1",
          "sha256": "d8a8bbc42524559a1ec397f530d6ac05f833c51b3bbeddaaee5a2970b8a2d494",
          "sha1": "625ba0ab564a9179b45d40b614ed556063207d9c",
          "md5": "8135996667a32140a4b8d37dd4061663"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.gradm",
          "module": "gradm-runtime",
          "version": {
            "requires": "4.0.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradm-integration-api-4.0.0-beta03.jar",
          "url": "gradm-integration-api-4.0.0-beta03.jar",
          "size": 27446,
          "sha512": "b0a1f25b99c0009d25250057fd3a54a6d3750773df3abf4e03bbee1f5d3e60c42c43bbee71ae95623d7c68df85771d39c18a324c5958dab3d4355aab7730ccd1",
          "sha256": "d8a8bbc42524559a1ec397f530d6ac05f833c51b3bbeddaaee5a2970b8a2d494",
          "sha1": "625ba0ab564a9179b45d40b614ed556063207d9c",
          "md5": "8135996667a32140a4b8d37dd4061663"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradm-integration-api-4.0.0-beta03-sources.jar",
          "url": "gradm-integration-api-4.0.0-beta03-sources.jar",
          "size": 8743,
          "sha512": "5a5d85add4b16048458ad5fdfc97eca9a4f8f8ad63aa723cf6082cc64cb5530e6d58d7488cfd42c1430d50eded42a77f7f5458f7d6e7618882fb3319aa728f82",
          "sha256": "3b24fc05d02d436d038bc6b013401cc0aa1e12353c0a723201df4f61b7ab22da",
          "sha1": "288189a62c9c2be52667fedc1d3682fa29a91126",
          "md5": "ca13562a9a2f48cb5108741a24881918"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradm-integration-api-4.0.0-beta03-javadoc.jar",
          "url": "gradm-integration-api-4.0.0-beta03-javadoc.jar",
          "size": 261,
          "sha512": "c47e851e6dae064e0ea4972628993ce47a1c15c3c874abc86a7d304d66f6bcdbfb05925349d0f7de9297c5718b49bbc69496ab9bba5380b2173b68a84ed9ad4c",
          "sha256": "9fa39bba66b96c00172b1aae9a934bdf7a3f345dfa477623741f3d3fdc6bdfe5",
          "sha1": "f27ba220ba8f21ef162636bbc3de70b0a97239f2",
          "md5": "074934b54c2c6377a6c5d657abe66903"
        }
      ]
    }
  ]
}
