{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.consensus",
    "module": "consensus-api",
    "version": "0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "consensus-api-0.16.0.jar",
          "url": "consensus-api-0.16.0.jar",
          "size": 77176,
          "sha512": "0f009dc5c6dc79306b61db1e28ec3cd9814b5a997cf3f73deeff16e90e7db500d86d18c84e36dfae015226412f53179099c2824b9151556761782f0446997d47",
          "sha256": "3de15c0fc9a1bd37ac0217feaa1ddfe971ea8883633edd367278cebc676a32f3",
          "sha1": "33f091f681962c186043eeaa68bef30c380b81cb",
          "md5": "010040bd8fe75e0a1d37a047b04705b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "consensus-api-0.16.0.jar",
          "url": "consensus-api-0.16.0.jar",
          "size": 77176,
          "sha512": "0f009dc5c6dc79306b61db1e28ec3cd9814b5a997cf3f73deeff16e90e7db500d86d18c84e36dfae015226412f53179099c2824b9151556761782f0446997d47",
          "sha256": "3de15c0fc9a1bd37ac0217feaa1ddfe971ea8883633edd367278cebc676a32f3",
          "sha1": "33f091f681962c186043eeaa68bef30c380b81cb",
          "md5": "010040bd8fe75e0a1d37a047b04705b0"
        }
      ]
    }
  ]
}
