{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.consensus",
    "module": "consensus-git",
    "version": "0.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "consensus-git-0.17.0.jar",
          "url": "consensus-git-0.17.0.jar",
          "size": 38779,
          "sha512": "58eeca5e6c28f82e35bc7decade33bde5937120115c7d6e5bad09e7e3a181bd4f572decad1bd553ca485448f21dffc9d68a95a28161f3bb0bd9479d8b5b02923",
          "sha256": "9e31345e824267c0878dfaa6d636d1644cc6b080ffe655c32d702ede215decb1",
          "sha1": "f966ebf45c692be43d8294b06a8cf193197a11fa",
          "md5": "dd8ab730b371bc60dd1febc4002a7d84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.consensus",
          "module": "consensus-api",
          "version": {
            "requires": "0.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "consensus-git-0.17.0.jar",
          "url": "consensus-git-0.17.0.jar",
          "size": 38779,
          "sha512": "58eeca5e6c28f82e35bc7decade33bde5937120115c7d6e5bad09e7e3a181bd4f572decad1bd553ca485448f21dffc9d68a95a28161f3bb0bd9479d8b5b02923",
          "sha256": "9e31345e824267c0878dfaa6d636d1644cc6b080ffe655c32d702ede215decb1",
          "sha1": "f966ebf45c692be43d8294b06a8cf193197a11fa",
          "md5": "dd8ab730b371bc60dd1febc4002a7d84"
        }
      ]
    }
  ]
}
