{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-jna/0.9.0/delusion-jna-0.9.0.module",
    "group": "me.omico.delusion",
    "module": "delusion-jna",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-jna-desktop-0.9.0.jar",
          "url": "delusion-jna-desktop-0.9.0.jar",
          "size": 11856,
          "sha512": "a493a581c990b5aaff05f73d433dee033f718d590aee879f4324ca35311829fad014aaffef0258d1642be284d9e3aa45dbb54d4d1dc9d6a949dedbccc57d7453",
          "sha256": "483407c7d8b95690c8445186cfaf3b92ded711081e42353e942630aee775a966",
          "sha1": "0c8de18284bcfd35301e33ba55c0491017859d08",
          "md5": "e69ad1e1865c7f5524155685bb95fc47"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "me.omico.delusion",
          "module": "delusion-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-jna-desktop-0.9.0.jar",
          "url": "delusion-jna-desktop-0.9.0.jar",
          "size": 11856,
          "sha512": "a493a581c990b5aaff05f73d433dee033f718d590aee879f4324ca35311829fad014aaffef0258d1642be284d9e3aa45dbb54d4d1dc9d6a949dedbccc57d7453",
          "sha256": "483407c7d8b95690c8445186cfaf3b92ded711081e42353e942630aee775a966",
          "sha1": "0c8de18284bcfd35301e33ba55c0491017859d08",
          "md5": "e69ad1e1865c7f5524155685bb95fc47"
        }
      ]
    }
  ]
}
