{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-core/0.8.0/delusion-core-0.8.0.module",
    "group": "me.omico.delusion",
    "module": "delusion-core",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-core-release.aar",
          "url": "delusion-core-android-0.8.0.aar",
          "size": 5200,
          "sha512": "41e6bb3ec8691f41d4bc5c2598c7b59fdbee1f28bc24cc3928d59702061e4da78d352783a6c4a1297f052aa157bd70a4a15d7be4d84d7a2d89ff2bdb1dc662f2",
          "sha256": "a302036d670e5cc72277cec8cc652973bc8c2238948f38ac4477dc18f5dc844c",
          "sha1": "9089a769a9ee5d2e2400049a4863fbc51a8f3bd0",
          "md5": "5ede134ad0b311eb8bbb005adcbc0e7d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "delusion-core-release.aar",
          "url": "delusion-core-android-0.8.0.aar",
          "size": 5200,
          "sha512": "41e6bb3ec8691f41d4bc5c2598c7b59fdbee1f28bc24cc3928d59702061e4da78d352783a6c4a1297f052aa157bd70a4a15d7be4d84d7a2d89ff2bdb1dc662f2",
          "sha256": "a302036d670e5cc72277cec8cc652973bc8c2238948f38ac4477dc18f5dc844c",
          "sha1": "9089a769a9ee5d2e2400049a4863fbc51a8f3bd0",
          "md5": "5ede134ad0b311eb8bbb005adcbc0e7d"
        }
      ]
    }
  ]
}
