{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.kami",
    "module": "kami-core",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kami-core-0.4.0.jar",
          "url": "kami-core-0.4.0.jar",
          "size": 12005,
          "sha512": "d6f9a40d2574cbffafee24a12c0df1b1650b529cbad5cb26e1c4679eeeb1e839e095ddd9da04880711382d3e0ebd1f869d4e7974a9d34f04f4ce9f0224a74a29",
          "sha256": "b5c21ef74b9feb3e2b56be963c2a2189f670f7e9752df297f175d359c79c6f20",
          "sha1": "3b3841449ad01d59acecfab0b8658080a2e087e6",
          "md5": "74bfafa2000098e548a553114ac631c7"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kami-core-0.4.0.jar",
          "url": "kami-core-0.4.0.jar",
          "size": 12005,
          "sha512": "d6f9a40d2574cbffafee24a12c0df1b1650b529cbad5cb26e1c4679eeeb1e839e095ddd9da04880711382d3e0ebd1f869d4e7974a9d34f04f4ce9f0224a74a29",
          "sha256": "b5c21ef74b9feb3e2b56be963c2a2189f670f7e9752df297f175d359c79c6f20",
          "sha1": "3b3841449ad01d59acecfab0b8658080a2e087e6",
          "md5": "74bfafa2000098e548a553114ac631c7"
        }
      ]
    }
  ]
}
