{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.consensus",
    "module": "consensus-dsl",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.consensus",
          "module": "consensus-api",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "consensus-dsl-0.8.0.jar",
          "url": "consensus-dsl-0.8.0.jar",
          "size": 13642,
          "sha512": "001e9eefc1eb909c0449ded6d999867e4638497b2f61a0390dcc66cc61181d7324ef2eaa70697662bebc11fce645f3bb4497bf256df4ab164eb580ba2d1af746",
          "sha256": "a48c86ca80e0dc20ff0c371e82b8a4bac8d9698178eb4f2fd2a55ae1abaf9fd7",
          "sha1": "3fca766918f9c49574ad8f93e2146f1e3d972f6d",
          "md5": "7e73f12580fa6a646b49d71893c6a052"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.consensus",
          "module": "consensus-api",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "consensus-dsl-0.8.0.jar",
          "url": "consensus-dsl-0.8.0.jar",
          "size": 13642,
          "sha512": "001e9eefc1eb909c0449ded6d999867e4638497b2f61a0390dcc66cc61181d7324ef2eaa70697662bebc11fce645f3bb4497bf256df4ab164eb580ba2d1af746",
          "sha256": "a48c86ca80e0dc20ff0c371e82b8a4bac8d9698178eb4f2fd2a55ae1abaf9fd7",
          "sha1": "3fca766918f9c49574ad8f93e2146f1e3d972f6d",
          "md5": "7e73f12580fa6a646b49d71893c6a052"
        }
      ]
    }
  ]
}
