{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-parcelize/0.9.0/delusion-parcelize-0.9.0.module",
    "group": "me.omico.delusion",
    "module": "delusion-parcelize",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-parcelize-release.aar",
          "url": "delusion-parcelize-android-0.9.0.aar",
          "size": 3883,
          "sha512": "e1d30610f7736e19c817b9f6488b1e110967f0e1ce2a7a20fdff74f1b4f3443a033494d0f7ad22a5d4375de75c7ae993102205b1641fd73d5407ba0810b2fbda",
          "sha256": "06fd226caa3d4b87013bd9f9d8e5122d367376e1583a4062d550205a0c8987a4",
          "sha1": "e091bbed535b5ee24a652147c6c42c0c21b640b4",
          "md5": "1fef667d52f1517f34bb352dd2a26d4c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "delusion-parcelize-release.aar",
          "url": "delusion-parcelize-android-0.9.0.aar",
          "size": 3883,
          "sha512": "e1d30610f7736e19c817b9f6488b1e110967f0e1ce2a7a20fdff74f1b4f3443a033494d0f7ad22a5d4375de75c7ae993102205b1641fd73d5407ba0810b2fbda",
          "sha256": "06fd226caa3d4b87013bd9f9d8e5122d367376e1583a4062d550205a0c8987a4",
          "sha1": "e091bbed535b5ee24a652147c6c42c0c21b640b4",
          "md5": "1fef667d52f1517f34bb352dd2a26d4c"
        }
      ]
    }
  ]
}
