{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-jna/0.7.0/delusion-jna-0.7.0.module",
    "group": "me.omico.delusion",
    "module": "delusion-jna",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-jna-release.aar",
          "url": "delusion-jna-android-0.7.0.aar",
          "size": 815,
          "sha512": "c90e8aa960ae8a822fe02d3df75d4aabd783dfd52b7e8694fe0f95e161bc911b9b5176a0749ef0271e256064aef1e650579ac41504397917365574d278cd2375",
          "sha256": "b714e1136f7b237a4d05770d8a8d0fb2b99ae1aa6d9b32b8caf0b4df21b3e40f",
          "sha1": "79694fe812f10ca9911d152610ab151e33fba58c",
          "md5": "8d7b0d04f77ac4a8219e9888000b307e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "delusion-jna-release.aar",
          "url": "delusion-jna-android-0.7.0.aar",
          "size": 815,
          "sha512": "c90e8aa960ae8a822fe02d3df75d4aabd783dfd52b7e8694fe0f95e161bc911b9b5176a0749ef0271e256064aef1e650579ac41504397917365574d278cd2375",
          "sha256": "b714e1136f7b237a4d05770d8a8d0fb2b99ae1aa6d9b32b8caf0b4df21b3e40f",
          "sha1": "79694fe812f10ca9911d152610ab151e33fba58c",
          "md5": "8d7b0d04f77ac4a8219e9888000b307e"
        }
      ]
    }
  ]
}
