{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-compose/0.11.2/delusion-compose-0.11.2.module",
    "group": "me.omico.delusion",
    "module": "delusion-compose",
    "version": "0.11.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-compose-wasm-js-0.11.2.klib",
          "url": "delusion-compose-wasm-js-0.11.2.klib",
          "size": 33411,
          "sha512": "995be25b5da68a48ede9fc4213d20fc4b8177defd4bf35cadf7a9f26e44a27a4eb9aed89502c14406acd9b9c5ef7c385197ba03fb5964406ae73739d09bff296",
          "sha256": "25ed58fe1fdca3347e331304ff9da7d8fe915e17457b12ed98e2421599b5bb75",
          "sha1": "a73f024531499783e68cb5dd550742521e71fb55",
          "md5": "546267ca02fde45e41cf09e3b0834008"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-compose-wasm-js-0.11.2.klib",
          "url": "delusion-compose-wasm-js-0.11.2.klib",
          "size": 33411,
          "sha512": "995be25b5da68a48ede9fc4213d20fc4b8177defd4bf35cadf7a9f26e44a27a4eb9aed89502c14406acd9b9c5ef7c385197ba03fb5964406ae73739d09bff296",
          "sha256": "25ed58fe1fdca3347e331304ff9da7d8fe915e17457b12ed98e2421599b5bb75",
          "sha1": "a73f024531499783e68cb5dd550742521e71fb55",
          "md5": "546267ca02fde45e41cf09e3b0834008"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-compose-0.11.2.kotlin_resources.zip",
          "url": "delusion-compose-wasm-js-0.11.2-kotlin_resources.kotlin_resources.zip",
          "size": 318,
          "sha512": "e4f9de7c7bac8aa2eb977827f1bb2f4a63faa96c5433b540a706d13df4ef2f50db67922b293a0a65b0dc371b42c2195234449b18b2f4951eb0e3617c47bc8af4",
          "sha256": "43dd7a04cd4956f37be35c2ac3558102c87a23789e061c70f7538b46eb9cd01b",
          "sha1": "d1264f9b51ac9d917b77a642d8b2bf467ece3061",
          "md5": "c75b838d1a26458161890ab376a72629"
        }
      ]
    }
  ]
}
