{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-kotlinx-io/0.11.2/delusion-kotlinx-io-0.11.2.module",
    "group": "me.omico.delusion",
    "module": "delusion-kotlinx-io",
    "version": "0.11.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-kotlinx-io-jvm-0.11.2.jar",
          "url": "delusion-kotlinx-io-jvm-0.11.2.jar",
          "size": 2981,
          "sha512": "06882402afb9d84b80e8b5e23a867c7b42adc1781e836cfcf02e16551957a1f12958b8a7480bf5551e09cb6e3da513cf58f3ee15ff316ec75cd39331d3cf67b7",
          "sha256": "1216705914739838f071aa23331be4fed683ced716d7c8ac27d2ac93c3db29e1",
          "sha1": "1d51417042de1df866f37fee24e2ce0b9379945a",
          "md5": "5c9f5e64a8d5a5459c61eabff9482e4b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-kotlinx-io-jvm-0.11.2.jar",
          "url": "delusion-kotlinx-io-jvm-0.11.2.jar",
          "size": 2981,
          "sha512": "06882402afb9d84b80e8b5e23a867c7b42adc1781e836cfcf02e16551957a1f12958b8a7480bf5551e09cb6e3da513cf58f3ee15ff316ec75cd39331d3cf67b7",
          "sha256": "1216705914739838f071aa23331be4fed683ced716d7c8ac27d2ac93c3db29e1",
          "sha1": "1d51417042de1df866f37fee24e2ce0b9379945a",
          "md5": "5c9f5e64a8d5a5459c61eabff9482e4b"
        }
      ]
    }
  ]
}
