{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-okio/0.11.0/delusion-okio-0.11.0.module",
    "group": "me.omico.delusion",
    "module": "delusion-okio",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-okio-jvm-0.11.0.jar",
          "url": "delusion-okio-jvm-0.11.0.jar",
          "size": 6999,
          "sha512": "fdf20e60c12517fb1dd269fb4de582e2c252c430147d220a9e44585f7b669110b17955ee54b5c810ca8c1d2c08e9368db5a672669f9702c32b18b286f0d3b646",
          "sha256": "97914cc994dfca1411be6fbb6e120019f583c4296ca183fc8ce39cb047626e76",
          "sha1": "bd36c68f5efc772a7a9b0b7eb7aa0dca3f2fc2ff",
          "md5": "e91725b95c0666e414ce0216d7f5d114"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-okio-jvm-0.11.0.jar",
          "url": "delusion-okio-jvm-0.11.0.jar",
          "size": 6999,
          "sha512": "fdf20e60c12517fb1dd269fb4de582e2c252c430147d220a9e44585f7b669110b17955ee54b5c810ca8c1d2c08e9368db5a672669f9702c32b18b286f0d3b646",
          "sha256": "97914cc994dfca1411be6fbb6e120019f583c4296ca183fc8ce39cb047626e76",
          "sha1": "bd36c68f5efc772a7a9b0b7eb7aa0dca3f2fc2ff",
          "md5": "e91725b95c0666e414ce0216d7f5d114"
        }
      ]
    }
  ]
}
