{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.consensus",
    "module": "consensus-gradle-plugins",
    "version": "0.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.consensus",
          "module": "consensus-api",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-build-configurations",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-git",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-initialization",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-publishing",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-root",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-spotless",
          "version": {
            "requires": "0.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "consensus-gradle-plugins-0.17.2.jar",
          "url": "consensus-gradle-plugins-0.17.2.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.consensus",
          "module": "consensus-api",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-build-configurations",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-git",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-initialization",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-publishing",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-root",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-spotless",
          "version": {
            "requires": "0.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "consensus-gradle-plugins-0.17.2.jar",
          "url": "consensus-gradle-plugins-0.17.2.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
