{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-okio/0.11.2/delusion-okio-0.11.2.module",
    "group": "me.omico.delusion",
    "module": "delusion-okio",
    "version": "0.11.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-okio.klib",
          "url": "delusion-okio-mingwx64-0.11.2.klib",
          "size": 9452,
          "sha512": "eadeec1e620d6a717382ce96e3a17719fe4876ebb6d73e257cef1d009c22022051ace778e55c359fba08fd01565c8304fdcb118d49d0b8d21bebde9eda7bd38c",
          "sha256": "47f15116472dec6189fb127a8a6f97d8ff0a0d8f5a00f358f404ff37554bd227",
          "sha1": "92c6012600f0be9aae19c148181024d7125a654a",
          "md5": "c3426e3bb46a382cb320bd7ca90230b4"
        }
      ]
    }
  ]
}
