{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.delusion",
    "module": "delusion-kotlinx-datetime",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-kotlinx-datetime-metadata-0.3.0.jar",
          "url": "delusion-kotlinx-datetime-0.3.0.jar",
          "size": 696,
          "sha512": "b2aeb78e51c2ca9583f4c19af65e80a951af12d8e5c52d44b5071cc3bc0b2bc4f7337f5375653f03f730e80e5c8b0f6b77759a9b6f9a28a26dedb64b6c38434c",
          "sha256": "600ea626d90ee3ebfe1b22309382baa33017082a277ed084d45102d67468c009",
          "sha1": "078bcf7072836e455d49f821ff63b078171efd12",
          "md5": "8a1740260c15aece104d46004eed4cfb"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "project.target.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../delusion-kotlinx-datetime-jvm/0.3.0/delusion-kotlinx-datetime-jvm-0.3.0.module",
        "group": "me.omico.delusion",
        "module": "delusion-kotlinx-datetime-jvm",
        "version": "0.3.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "project.target.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../delusion-kotlinx-datetime-jvm/0.3.0/delusion-kotlinx-datetime-jvm-0.3.0.module",
        "group": "me.omico.delusion",
        "module": "delusion-kotlinx-datetime-jvm",
        "version": "0.3.0"
      }
    }
  ]
}
