{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.elucidator",
    "module": "elucidator",
    "version": "0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "elucidator-0.16.0.jar",
          "url": "elucidator-0.16.0.jar",
          "size": 79586,
          "sha512": "a6dc645e1af5668e7e8bb45222da360fe8d98e4a2411aa4fc4c6e0c61713c1522da809ab2dfbdde8e6d99ce02a6dcda11b9e1d5facbb9628c1d6e9d993da5426",
          "sha256": "f66074b487ba963c65822051c530354fa3dee53b6f6831b4330cde38035e5c40",
          "sha1": "0b9222bf798dbb6f714c9f2dc40f6ade2c0fd51b",
          "md5": "f49c225a00f8c11b8f437a0fa512e206"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "elucidator-0.16.0.jar",
          "url": "elucidator-0.16.0.jar",
          "size": 79586,
          "sha512": "a6dc645e1af5668e7e8bb45222da360fe8d98e4a2411aa4fc4c6e0c61713c1522da809ab2dfbdde8e6d99ce02a6dcda11b9e1d5facbb9628c1d6e9d993da5426",
          "sha256": "f66074b487ba963c65822051c530354fa3dee53b6f6831b4330cde38035e5c40",
          "sha1": "0b9222bf798dbb6f714c9f2dc40f6ade2c0fd51b",
          "md5": "f49c225a00f8c11b8f437a0fa512e206"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "elucidator-0.16.0-sources.jar",
          "url": "elucidator-0.16.0-sources.jar",
          "size": 19131,
          "sha512": "c3456eff4f6762876e4bca2ddb531a21c156dee070c2d26314c44357765a71338d07bff6db68eb4ba4b9b616e2176e3f1b3db95ec35871fafc9b7e9536779bbc",
          "sha256": "ec58f7d143d246e09b6babe307dc9bffc9434452b25baa03764f535564cf889a",
          "sha1": "289acb855fe76172c4ac626589728016f7bba585",
          "md5": "7de547df5b20f37edd4cc6099e1f606f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "elucidator-0.16.0-javadoc.jar",
          "url": "elucidator-0.16.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
