{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.delusion",
    "module": "delusion-kotlin-compiler-embeddable",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-kotlin-compiler-embeddable-metadata-0.9.0.jar",
          "url": "delusion-kotlin-compiler-embeddable-0.9.0.jar",
          "size": 647,
          "sha512": "f9c081b46244233787a52aabb776722b019e9521c3a89a6b4e55a669be9cfee3411764e79d1de9563bc03c6e61e4fe541deee4b30affd96a14de6dd2fdca1dc9",
          "sha256": "089e24417bf9f6c34eec5720eebb2cbcc82ea2855ecef90133eb17e1079d5868",
          "sha1": "28cbbd267e2cdbea0a637d71db8f57b788a419c0",
          "md5": "ba0b1a9fde0b67f9902aec928b1936fb"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../delusion-kotlin-compiler-embeddable-jvm/0.9.0/delusion-kotlin-compiler-embeddable-jvm-0.9.0.module",
        "group": "me.omico.delusion",
        "module": "delusion-kotlin-compiler-embeddable-jvm",
        "version": "0.9.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../delusion-kotlin-compiler-embeddable-jvm/0.9.0/delusion-kotlin-compiler-embeddable-jvm-0.9.0.module",
        "group": "me.omico.delusion",
        "module": "delusion-kotlin-compiler-embeddable-jvm",
        "version": "0.9.0"
      }
    }
  ]
}
