{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-parcelize/0.11.2/delusion-parcelize-0.11.2.module",
    "group": "me.omico.delusion",
    "module": "delusion-parcelize",
    "version": "0.11.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-parcelize-release.aar",
          "url": "delusion-parcelize-android-0.11.2.aar",
          "size": 3556,
          "sha512": "9235c67bfa3dda534158358322907bc0215682b5deca4bbd233069ac8bd04624b212b7aa76e3e1ba1b4c38502b1092594fc1c52d58adc15e5e987ac3225c14e4",
          "sha256": "f7c94a76ab2790253d3415f310e25898b60850af21a5978c468ef794f5a2fad4",
          "sha1": "34aaacbc0becf0e839e07e46ed5b80c6f2a444f5",
          "md5": "3062085f691566b7c67050268de3f020"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-parcelize-release.aar",
          "url": "delusion-parcelize-android-0.11.2.aar",
          "size": 3556,
          "sha512": "9235c67bfa3dda534158358322907bc0215682b5deca4bbd233069ac8bd04624b212b7aa76e3e1ba1b4c38502b1092594fc1c52d58adc15e5e987ac3225c14e4",
          "sha256": "f7c94a76ab2790253d3415f310e25898b60850af21a5978c468ef794f5a2fad4",
          "sha1": "34aaacbc0becf0e839e07e46ed5b80c6f2a444f5",
          "md5": "3062085f691566b7c67050268de3f020"
        }
      ]
    }
  ]
}
