{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.delusion",
    "module": "delusion-kotlin-compiler-embeddable",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-kotlin-compiler-embeddable-metadata-0.4.0.jar",
          "url": "delusion-kotlin-compiler-embeddable-0.4.0.jar",
          "size": 670,
          "sha512": "c3be9ce05a835030c5582975b5ab61f9b5af86bf9f2cf3c940d4746c9f58ac13d6086b2d3553aa41dd869008f846f40b6bb310e115cefbeb50aaf94ceb4f5fa7",
          "sha256": "fbc64f5c44a7added8b6eab517cf7d70555e25153bf5d44a6ed9b0e5312f7de9",
          "sha1": "b94fe605ea8ff0f68f3feab065ae0b7d67860964",
          "md5": "31d8d2ec69675d5797a0e290b0e3cd54"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "project.target.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../delusion-kotlin-compiler-embeddable-jvm/0.4.0/delusion-kotlin-compiler-embeddable-jvm-0.4.0.module",
        "group": "me.omico.delusion",
        "module": "delusion-kotlin-compiler-embeddable-jvm",
        "version": "0.4.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "project.target.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../delusion-kotlin-compiler-embeddable-jvm/0.4.0/delusion-kotlin-compiler-embeddable-jvm-0.4.0.module",
        "group": "me.omico.delusion",
        "module": "delusion-kotlin-compiler-embeddable-jvm",
        "version": "0.4.0"
      }
    }
  ]
}
