{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.merlin",
    "module": "merlin-runtime",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "merlin-runtime-0.2.0.jar",
          "url": "merlin-runtime-0.2.0.jar",
          "size": 26867,
          "sha512": "7c8fac1427e431ae55bb52d3d077a43c2bdef24806c60c954b341699dd9e73f8e69febd2c3f1e95f0bd7eca3d7899dd9685166ba128545a84fcf14da36b4d4d7",
          "sha256": "404c8c6c5cf7a2e3a9de06796b869a2bddb63d3ebfe4ba59e43b1d05cf5c6f03",
          "sha1": "87543589dda11736cb2b6ef039b20910b430a978",
          "md5": "75cdb10da0a7a2d950dfac0cb4b57f2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "merlin-runtime-0.2.0.jar",
          "url": "merlin-runtime-0.2.0.jar",
          "size": 26867,
          "sha512": "7c8fac1427e431ae55bb52d3d077a43c2bdef24806c60c954b341699dd9e73f8e69febd2c3f1e95f0bd7eca3d7899dd9685166ba128545a84fcf14da36b4d4d7",
          "sha256": "404c8c6c5cf7a2e3a9de06796b869a2bddb63d3ebfe4ba59e43b1d05cf5c6f03",
          "sha1": "87543589dda11736cb2b6ef039b20910b430a978",
          "md5": "75cdb10da0a7a2d950dfac0cb4b57f2a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "merlin-runtime-0.2.0-sources.jar",
          "url": "merlin-runtime-0.2.0-sources.jar",
          "size": 2344,
          "sha512": "715032c9decf254bcd3de3c8e1333e6cf13d105a93e9e3114df515fb200146043666258706e55eff7db6493132431f520e04220a6230649e70450d62a54da1d9",
          "sha256": "080781ac95c6e1362b09cc11ed9796f08806c99ba2a0e23658417b7a3e0a6b1c",
          "sha1": "bf659ecd5d2fe9d15e15da0840f1f62645aaee5f",
          "md5": "70e8d99b86018eb9690604da2e9b80ce"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "merlin-runtime-0.2.0-javadoc.jar",
          "url": "merlin-runtime-0.2.0-javadoc.jar",
          "size": 261,
          "sha512": "fee6f7bdd55ce23941efb71efbbf991ac6c08ad4efc4bd79c4f4dd4c968dc89b1582085a2b209362a05e19737add0093716dc1ecee4be0bde8abbce34bba749a",
          "sha256": "e50c22b399ab325914b0f0c791545a68e7b9aa7aad27e2935fd2582b0c300942",
          "sha1": "df0a611b6982037a649196edf2f7876412bcb937",
          "md5": "8c73e46055eb83c1c670e1fba5b63c97"
        }
      ]
    }
  ]
}
