{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-compose/0.11.2/delusion-compose-0.11.2.module",
    "group": "me.omico.delusion",
    "module": "delusion-compose",
    "version": "0.11.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-compose-release.aar",
          "url": "delusion-compose-android-0.11.2.aar",
          "size": 32708,
          "sha512": "081a8fa9add8c9e65294084de486a29a63aee0facbc38b5120cdecb281a1a34510fe5e1b2a2284826d1c84394076b26b5fe42f998392edf624d431f20d2df05c",
          "sha256": "3b2fdfd99894ae3c22ed61e6f49493524af9adaa1eaa423fccb875aa3885a29b",
          "sha1": "4e11c8d3fd0fe954e2fd9f81d0cf564b5b00b072",
          "md5": "49580e512dd9019ebcba3c51d7aa0a76"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "delusion-compose-release.aar",
          "url": "delusion-compose-android-0.11.2.aar",
          "size": 32708,
          "sha512": "081a8fa9add8c9e65294084de486a29a63aee0facbc38b5120cdecb281a1a34510fe5e1b2a2284826d1c84394076b26b5fe42f998392edf624d431f20d2df05c",
          "sha256": "3b2fdfd99894ae3c22ed61e6f49493524af9adaa1eaa423fccb875aa3885a29b",
          "sha1": "4e11c8d3fd0fe954e2fd9f81d0cf564b5b00b072",
          "md5": "49580e512dd9019ebcba3c51d7aa0a76"
        }
      ]
    }
  ]
}
