{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.delusion",
    "module": "delusion-core",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-core-metadata-0.11.0.jar",
          "url": "delusion-core-0.11.0.jar",
          "size": 721,
          "sha512": "40c9409dfee2692ae824e56ee127211687a5a4fa2b157f07f86ded8e5a5aed61f4e6c06a3f49b511b77e4a41fce7c5720d09d6b25bcfccac7f259b6fd388c3cb",
          "sha256": "c9c1440e7323ef82eefd622c6ab8586811b731880cceee6f00d47b4d6b148f23",
          "sha1": "6868fb0e6575ec3dacca59c93a17d01da228761c",
          "md5": "62aee3dd3e83cef76ad866f4a35df69c"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../delusion-core-android/0.11.0/delusion-core-android-0.11.0.module",
        "group": "me.omico.delusion",
        "module": "delusion-core-android",
        "version": "0.11.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../delusion-core-android/0.11.0/delusion-core-android-0.11.0.module",
        "group": "me.omico.delusion",
        "module": "delusion-core-android",
        "version": "0.11.0"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../delusion-core-desktop/0.11.0/delusion-core-desktop-0.11.0.module",
        "group": "me.omico.delusion",
        "module": "delusion-core-desktop",
        "version": "0.11.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../delusion-core-desktop/0.11.0/delusion-core-desktop-0.11.0.module",
        "group": "me.omico.delusion",
        "module": "delusion-core-desktop",
        "version": "0.11.0"
      }
    }
  ]
}
