{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.kami",
    "module": "kami-kotlin",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.kami",
          "module": "kami-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.20-2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.compose",
          "module": "org.jetbrains.kotlin.plugin.compose.gradle.plugin",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.parcelize",
          "module": "org.jetbrains.kotlin.plugin.parcelize.gradle.plugin",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx.atomicfu",
          "module": "org.jetbrains.kotlinx.atomicfu.gradle.plugin",
          "version": {
            "requires": "0.27.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kami-kotlin-0.5.0.jar",
          "url": "kami-kotlin-0.5.0.jar",
          "size": 89361,
          "sha512": "0a9c672ce09f31c032cf9b908b7491ab65c930a71f8767fbfca6138cbba7b1fb76ffc93b430467da9ba652174b92e5dbf9a66b524ba983cf889e84f9ef0f2932",
          "sha256": "0924e74246ace4f0a4fe97ac2c48f9af31dd6e45ca4a724a72f96377eaa80e1d",
          "sha1": "09dbbf754c6f6ec324648e46607d137ddb810903",
          "md5": "ab2cb5b4a1064d95b532f1a8b52c571b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.kami",
          "module": "kami-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.20-2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.compose",
          "module": "org.jetbrains.kotlin.plugin.compose.gradle.plugin",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.parcelize",
          "module": "org.jetbrains.kotlin.plugin.parcelize.gradle.plugin",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx.atomicfu",
          "module": "org.jetbrains.kotlinx.atomicfu.gradle.plugin",
          "version": {
            "requires": "0.27.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kami-kotlin-0.5.0.jar",
          "url": "kami-kotlin-0.5.0.jar",
          "size": 89361,
          "sha512": "0a9c672ce09f31c032cf9b908b7491ab65c930a71f8767fbfca6138cbba7b1fb76ffc93b430467da9ba652174b92e5dbf9a66b524ba983cf889e84f9ef0f2932",
          "sha256": "0924e74246ace4f0a4fe97ac2c48f9af31dd6e45ca4a724a72f96377eaa80e1d",
          "sha1": "09dbbf754c6f6ec324648e46607d137ddb810903",
          "md5": "ab2cb5b4a1064d95b532f1a8b52c571b"
        }
      ]
    }
  ]
}
