{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.consensus",
    "module": "consensus-dsl",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.consensus",
          "module": "consensus-api",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "consensus-dsl-0.5.0.jar",
          "url": "consensus-dsl-0.5.0.jar",
          "size": 10080,
          "sha512": "aa945f983ce41c0d16376c5790fc71f713bb495a24a4a5270c4acf25c371daa02aa4955b79730ac300ec711ab3ca323a25bfa19af0e0692fc80b872923163f62",
          "sha256": "b37434b5c20371065f04f536609a804ae721ec4618457f68a5a9b2d65b329a0d",
          "sha1": "4fe069284c73a60f5afcfed1b9827079a7af2b14",
          "md5": "645a7d2901df5b63485279850d072165"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.consensus",
          "module": "consensus-api",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "consensus-dsl-0.5.0.jar",
          "url": "consensus-dsl-0.5.0.jar",
          "size": 10080,
          "sha512": "aa945f983ce41c0d16376c5790fc71f713bb495a24a4a5270c4acf25c371daa02aa4955b79730ac300ec711ab3ca323a25bfa19af0e0692fc80b872923163f62",
          "sha256": "b37434b5c20371065f04f536609a804ae721ec4618457f68a5a9b2d65b329a0d",
          "sha1": "4fe069284c73a60f5afcfed1b9827079a7af2b14",
          "md5": "645a7d2901df5b63485279850d072165"
        }
      ]
    }
  ]
}
