{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.consensus",
    "module": "consensus-root",
    "version": "0.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "consensus-root-0.20.0.jar",
          "url": "consensus-root-0.20.0.jar",
          "size": 48760,
          "sha512": "1877cd07c75c1ac72f945ff81f97ec2e6dc79724f05f2b8d53e233940c35dbeb707c884caf5982a50a8e3879a4db33d7b4b5b48e5bf91228ea96e0f9feda0134",
          "sha256": "9ba40939478ca82d5b724214c8ba8c059dd9b6714e7c7e17f03e52e5d609b485",
          "sha1": "d0bcaddb0aab9742279dfa1eca7a01aa15d6fe75",
          "md5": "702a260407f344564e9942bdcb14ccd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.consensus",
          "module": "consensus-api",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "consensus-root-0.20.0.jar",
          "url": "consensus-root-0.20.0.jar",
          "size": 48760,
          "sha512": "1877cd07c75c1ac72f945ff81f97ec2e6dc79724f05f2b8d53e233940c35dbeb707c884caf5982a50a8e3879a4db33d7b4b5b48e5bf91228ea96e0f9feda0134",
          "sha256": "9ba40939478ca82d5b724214c8ba8c059dd9b6714e7c7e17f03e52e5d609b485",
          "sha1": "d0bcaddb0aab9742279dfa1eca7a01aa15d6fe75",
          "md5": "702a260407f344564e9942bdcb14ccd7"
        }
      ]
    }
  ]
}
