{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.consensus",
    "module": "consensus-spotless",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "consensus-spotless-0.5.0.jar",
          "url": "consensus-spotless-0.5.0.jar",
          "size": 31558,
          "sha512": "7cbd77c4fbe6c4d2cde9ede85c864a45cc0020f967688532e5796c66162c737bae9cebfb83a536194b1001531703e317a0b6931afdb97eda56ba38263ab8e62d",
          "sha256": "46cec77861df65daf5fc3491d1ed9c038364bcd4e5e7ab076a2f56361fd10a58",
          "sha1": "6bc451edb05598dd38d143f6317fde155dd1d23b",
          "md5": "2b48ec444b0e9f2d93da2d25f2d9277b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.consensus",
          "module": "consensus-api",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "me.omico.consensus",
          "module": "consensus-dsl",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "consensus-spotless-0.5.0.jar",
          "url": "consensus-spotless-0.5.0.jar",
          "size": 31558,
          "sha512": "7cbd77c4fbe6c4d2cde9ede85c864a45cc0020f967688532e5796c66162c737bae9cebfb83a536194b1001531703e317a0b6931afdb97eda56ba38263ab8e62d",
          "sha256": "46cec77861df65daf5fc3491d1ed9c038364bcd4e5e7ab076a2f56361fd10a58",
          "sha1": "6bc451edb05598dd38d143f6317fde155dd1d23b",
          "md5": "2b48ec444b0e9f2d93da2d25f2d9277b"
        }
      ]
    }
  ]
}
