{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-kotlinx-io/0.11.1/delusion-kotlinx-io-0.11.1.module",
    "group": "me.omico.delusion",
    "module": "delusion-kotlinx-io",
    "version": "0.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-kotlinx-io.klib",
          "url": "delusion-kotlinx-io-macosarm64-0.11.1.klib",
          "size": 6389,
          "sha512": "c92cb5e8f9ed5a3123d6847bbc30e6de54f6242405e9e069536b7266f51160525a955cfb8c858b40f1c36ea23b6adae31c38859f09b4d747205462a5eec7cfd6",
          "sha256": "3c94dcac4c101db6b69b3f097477140f992b12945a48ba8d05652d8add53dfde",
          "sha1": "85b55cf2c4b76865b52f260580bc79913ffc699d",
          "md5": "41d339e8ac08cd1dccea58c234ad98fc"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-kotlinx-io-macosarm64-0.11.1-metadata.jar",
          "url": "delusion-kotlinx-io-macosarm64-0.11.1-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
