{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-kotlin-compiler-embeddable/0.6.1/delusion-kotlin-compiler-embeddable-0.6.1.module",
    "group": "me.omico.delusion",
    "module": "delusion-kotlin-compiler-embeddable",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.delusion",
          "module": "delusion-kotlin-compiler",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-kotlin-compiler-embeddable-jvm-0.6.1.jar",
          "url": "delusion-kotlin-compiler-embeddable-jvm-0.6.1.jar",
          "size": 24504,
          "sha512": "e93aeec0197d38e0a1c20fcab1232aded5772227492be0012834a66a28ba8aca97f003b74f38bfe319e6facfeab9b8b0502a1443b7e98462fc652f0243159a35",
          "sha256": "b8e670a4d1892fe452460de396aa94fd03a15431f8df7412495ee26baa2c62d4",
          "sha1": "143984809b5697479949e5d6e4e99f83d2ac67c4",
          "md5": "4fc669b24651fbcb2b8a1bd4e97f4ede"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.delusion",
          "module": "delusion-kotlin-compiler",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-kotlin-compiler-embeddable-jvm-0.6.1.jar",
          "url": "delusion-kotlin-compiler-embeddable-jvm-0.6.1.jar",
          "size": 24504,
          "sha512": "e93aeec0197d38e0a1c20fcab1232aded5772227492be0012834a66a28ba8aca97f003b74f38bfe319e6facfeab9b8b0502a1443b7e98462fc652f0243159a35",
          "sha256": "b8e670a4d1892fe452460de396aa94fd03a15431f8df7412495ee26baa2c62d4",
          "sha1": "143984809b5697479949e5d6e4e99f83d2ac67c4",
          "md5": "4fc669b24651fbcb2b8a1bd4e97f4ede"
        }
      ]
    }
  ]
}
