{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-okio/0.10.0/delusion-okio-0.10.0.module",
    "group": "me.omico.delusion",
    "module": "delusion-okio",
    "version": "0.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-okio.klib",
          "url": "delusion-okio-linuxarm64-0.10.0.klib",
          "size": 9464,
          "sha512": "d7689f167ae5e337f4f13ed8b2ddc5641142944963f3a99e34658083ab51240f9784f54580e4d4d56b71d8411a99df931b84c410932c43e2da601230dc4bbbe9",
          "sha256": "0c748721361049a786dbb5bd715533adcd654fe8a6b4d3812b32a21a308845f9",
          "sha1": "e522a941cef94217f8dc0ea0db8889c3a72c72ff",
          "md5": "cf46d97aa25c3274243e0739cfd8db58"
        }
      ]
    }
  ]
}
