{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.consensus",
    "module": "consensus-api",
    "version": "0.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "consensus-api-0.17.2.jar",
          "url": "consensus-api-0.17.2.jar",
          "size": 77472,
          "sha512": "3a1a7d2eeb061f5d653adeff60a1dd243ff045ab0f8caf592fb850da1bdaa806599097ee1214126f93898b4c0f55085689f34470339201ce70e625dcfd818dd3",
          "sha256": "26ced5d029d2a8b716567e0755bf347661d497682b534410ae1f90c3ee350b7e",
          "sha1": "5fefa638651668eb69b2b4768e2404dd0ad5b97d",
          "md5": "406206a5b320e8d3815a92f3635f85ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "consensus-api-0.17.2.jar",
          "url": "consensus-api-0.17.2.jar",
          "size": 77472,
          "sha512": "3a1a7d2eeb061f5d653adeff60a1dd243ff045ab0f8caf592fb850da1bdaa806599097ee1214126f93898b4c0f55085689f34470339201ce70e625dcfd818dd3",
          "sha256": "26ced5d029d2a8b716567e0755bf347661d497682b534410ae1f90c3ee350b7e",
          "sha1": "5fefa638651668eb69b2b4768e2404dd0ad5b97d",
          "md5": "406206a5b320e8d3815a92f3635f85ef"
        }
      ]
    }
  ]
}
