{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-kotlinx-io/0.11.2/delusion-kotlinx-io-0.11.2.module",
    "group": "me.omico.delusion",
    "module": "delusion-kotlinx-io",
    "version": "0.11.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "webApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-kotlinx-io-web-0.11.2.klib",
          "url": "delusion-kotlinx-io-web-0.11.2.klib",
          "size": 5343,
          "sha512": "b0f7dfc4309280af8c0c16d01ba26c496965b90fb7b55fc9cb046dc8c6c4181ddb2cbbb08b50a9637b3a58a877d773d72bc511c58e6f51539877e871bfcfa786",
          "sha256": "a0888b44d2555c311a386c7ee206d02caa84d2646f316a288730b11233e41ec1",
          "sha1": "0f88bfed84e87083ac70a8e7d22706854b8c81e6",
          "md5": "35575cdda5771192b6cba6c06c8506fa"
        }
      ]
    },
    {
      "name": "webRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-kotlinx-io-web-0.11.2.klib",
          "url": "delusion-kotlinx-io-web-0.11.2.klib",
          "size": 5343,
          "sha512": "b0f7dfc4309280af8c0c16d01ba26c496965b90fb7b55fc9cb046dc8c6c4181ddb2cbbb08b50a9637b3a58a877d773d72bc511c58e6f51539877e871bfcfa786",
          "sha256": "a0888b44d2555c311a386c7ee206d02caa84d2646f316a288730b11233e41ec1",
          "sha1": "0f88bfed84e87083ac70a8e7d22706854b8c81e6",
          "md5": "35575cdda5771192b6cba6c06c8506fa"
        }
      ]
    }
  ]
}
