{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-okio/0.9.0/delusion-okio-0.9.0.module",
    "group": "me.omico.delusion",
    "module": "delusion-okio",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-okio.klib",
          "url": "delusion-okio-linuxx64-0.9.0.klib",
          "size": 10446,
          "sha512": "4ad0b6382bbc6d8b7b2f53890e7924c0205ba504322e3c1287da701bbeb9d23c7e750a41ea02d61e703912f52afc19308e315bbb42cac8a627f94c00b31a46b3",
          "sha256": "aadc41898c199b81bd166440b0c61c4a2fe12d34b3bdfa41c3e648be68960989",
          "sha1": "2d6fd0050541b52b403b408f83b79d497859533b",
          "md5": "7d6a939071684fdbcacdc7b720c62805"
        }
      ]
    }
  ]
}
