{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-parcelize/0.11.0/delusion-parcelize-0.11.0.module",
    "group": "me.omico.delusion",
    "module": "delusion-parcelize",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-parcelize-release.aar",
          "url": "delusion-parcelize-android-0.11.0.aar",
          "size": 3551,
          "sha512": "eae71ce058fd394ec0a888849f4614ca648ce0b8f42837b257e5729850293d824bcef6be8d72cb6de30e70ed13869731cfef57d711073e531af4e9edd237034e",
          "sha256": "d1e90f2554855937f7e39870de66cd621c82446f6ae2f25571336b70a5e6c59d",
          "sha1": "76616ffca4660e068387f43f6d6c8aeab65bc790",
          "md5": "da814dbc8bd4f87b1c9353a1fbd559f9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-parcelize-release.aar",
          "url": "delusion-parcelize-android-0.11.0.aar",
          "size": 3551,
          "sha512": "eae71ce058fd394ec0a888849f4614ca648ce0b8f42837b257e5729850293d824bcef6be8d72cb6de30e70ed13869731cfef57d711073e531af4e9edd237034e",
          "sha256": "d1e90f2554855937f7e39870de66cd621c82446f6ae2f25571336b70a5e6c59d",
          "sha1": "76616ffca4660e068387f43f6d6c8aeab65bc790",
          "md5": "da814dbc8bd4f87b1c9353a1fbd559f9"
        }
      ]
    }
  ]
}
