{
  "formatVersion": "1.1",
  "component": {
    "url": "../../delusion-core/0.9.0/delusion-core-0.9.0.module",
    "group": "me.omico.delusion",
    "module": "delusion-core",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "delusion-core-release.aar",
          "url": "delusion-core-android-0.9.0.aar",
          "size": 5180,
          "sha512": "597501b346050fa2a4f673fccb277f4e7fa4fe5c2e35fed25db0c38c4f2966587e9fd13fc0f90b7c20f24dc3f887d69483852beb5d4324e972692ee008b9730d",
          "sha256": "6f943dd80aadc8fcaf5f1717b74033671c622a71e9d4f7a1f40c8c97bbd912fb",
          "sha1": "1b76923a92af429886ba900650c93b9207527928",
          "md5": "5e1076cd8628c710ece11679858055d8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "delusion-core-release.aar",
          "url": "delusion-core-android-0.9.0.aar",
          "size": 5180,
          "sha512": "597501b346050fa2a4f673fccb277f4e7fa4fe5c2e35fed25db0c38c4f2966587e9fd13fc0f90b7c20f24dc3f887d69483852beb5d4324e972692ee008b9730d",
          "sha256": "6f943dd80aadc8fcaf5f1717b74033671c622a71e9d4f7a1f40c8c97bbd912fb",
          "sha1": "1b76923a92af429886ba900650c93b9207527928",
          "md5": "5e1076cd8628c710ece11679858055d8"
        }
      ]
    }
  ]
}
