{
  "formatVersion": "1.1",
  "component": {
    "group": "me.omico.consensus",
    "module": "consensus-r8",
    "version": "0.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "consensus-r8-0.20.2.jar",
          "url": "consensus-r8-0.20.2.jar",
          "size": 24062,
          "sha512": "e6108ec514bcdfc1e86433632d20192ad2e68580328967c2b9c30b48c6a3b7fd7dd96dbee83c330fa8354b0a0e87f5028a9ba5020cfad57d75bf0fb6134970de",
          "sha256": "a40d93d3e2b7b77796ab9a072e6dd4b01b3c53fcd535abd372617b60e83997c0",
          "sha1": "1fa215d6f2ed35ec24a610dfac4a8727f833b0b9",
          "md5": "a962fe30d944642fd53ea2361d5e5c67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.omico.consensus",
          "module": "consensus-api",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "r8",
          "version": {
            "requires": "8.5.35"
          }
        }
      ],
      "files": [
        {
          "name": "consensus-r8-0.20.2.jar",
          "url": "consensus-r8-0.20.2.jar",
          "size": 24062,
          "sha512": "e6108ec514bcdfc1e86433632d20192ad2e68580328967c2b9c30b48c6a3b7fd7dd96dbee83c330fa8354b0a0e87f5028a9ba5020cfad57d75bf0fb6134970de",
          "sha256": "a40d93d3e2b7b77796ab9a072e6dd4b01b3c53fcd535abd372617b60e83997c0",
          "sha1": "1fa215d6f2ed35ec24a610dfac4a8727f833b0b9",
          "md5": "a962fe30d944642fd53ea2361d5e5c67"
        }
      ]
    }
  ]
}
